version: '2'

volumes:
  peer1.org1.chinaso.com:

services:
  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=123
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for chinaso map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "7984:5984"

  peer1.org1.chinaso.com:
    container_name: peer1.org1.chinaso.com
    hostname: peer1.org1.chinaso.com
    image: hyperledger/fabric-peer:1.4.3
    environment:
#       - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=127.0.0.1:7984
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=user
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123
      - CORE_PEER_NETWORKID=etcdraftnetwork
      - CORE_PEER_ID=peer1.org1.chinaso.com
      - CORE_PEER_ADDRESS=peer1.org1.chinaso.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer1.org1.chinaso.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.chinaso.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      #- CORE_LOGGING_LEVEL=ERROR
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ../../../fixture/crypto-config/peerOrganizations/org1.chinaso.com/peers/peer1.org1.chinaso.com/msp:/etc/hyperledger/fabric/msp
      - ../../../fixture/crypto-config/peerOrganizations/org1.chinaso.com/peers/peer1.org1.chinaso.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:8051
      - 8052:8052
      - 8053:8053
    depends_on:
      - couchdb1
    networks:
      default:
        aliases:
          - etcdraftnetwork
    extra_hosts:
      - "orderer0.chinaso.com:127.0.0.1"
      - "orderer1.chinaso.com:127.0.0.1"
      - "orderer2.chinaso.com:127.0.0.1"
      - "orderer3.chinaso.com:127.0.0.1"
      - "orderer4.chinaso.com:127.0.0.1"
      - "peer0.org1.chinaso.com:127.0.0.1"
      - "peer1.org1.chinaso.com:127.0.0.1"